# Generated by Django 4.1.7 on 2023-03-15 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buckets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.CharField(max_length=30)),
                ('lien', models.CharField(max_length=30)),
                ('buckets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appone.buckets')),
            ],
        ),
        migrations.CreateModel(
            name='legs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('aero_depart', models.CharField(max_length=30)),
                ('aero_arrivee', models.CharField(max_length=30)),
                ('duree', models.CharField(max_length=30)),
                ('nbre_escale', models.CharField(max_length=30)),
                ('date_depart', models.CharField(max_length=30)),
                ('date_arrivee', models.CharField(max_length=30)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appone.items')),
            ],
        ),
        migrations.CreateModel(
            name='parametre_recherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('departureDate', models.CharField(max_length=30)),
                ('returnDate', models.CharField(max_length=30)),
                ('cabinClass', models.CharField(max_length=30)),
                ('currency', models.CharField(max_length=30)),
                ('adults', models.CharField(max_length=30)),
                ('childAge1', models.CharField(max_length=30)),
                ('childAge2', models.CharField(max_length=30)),
                ('childAge3', models.CharField(max_length=30)),
                ('childAge4', models.CharField(max_length=30)),
                ('childAge5', models.CharField(max_length=30)),
                ('childAge6', models.CharField(max_length=30)),
                ('childAge7', models.CharField(max_length=30)),
                ('childAge8', models.CharField(max_length=30)),
                ('dt_recherche', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='segments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aero_depart', models.CharField(max_length=30)),
                ('aero_arrivee', models.CharField(max_length=30)),
                ('duree', models.CharField(max_length=30)),
                ('date_depart', models.CharField(max_length=30)),
                ('date_arrivee', models.CharField(max_length=30)),
                ('compagnie', models.CharField(max_length=30)),
                ('vol_operepar', models.CharField(max_length=30)),
                ('legs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appone.legs')),
            ],
        ),
        migrations.AddField(
            model_name='buckets',
            name='parametre_recherche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appone.parametre_recherche'),
        ),
    ]
